import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  image: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bigContainer: {
    width: '90%',
    height: '90%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: 5,
    borderWidth: .5,
  },
  controls: {
    flexDirection: 'row',
  },
  playPauseContainer: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: '20%'
  },
  pauseSymbol: {
    width: 20,
    height: 25,
    backgroundColor: 'white',
    borderColor: 'black',
    borderRightWidth: 5,
    borderLeftWidth: 5,
  },
  triangleRight: {
  width: 0,
  height: 0,
  borderLeftWidth: 10,
  borderRightWidth: 10,
  borderBottomWidth: 30,
  borderStyle: 'solid',
  backgroundColor: 'transparent',
  borderLeftColor: 'transparent',
  borderRightColor: 'transparent',
  borderBottomColor: 'black',
  transform: [{rotate: '90deg'}],
  },
  options: {
    flexDirection: 'column',
    backgroundColor: 'white',
    height: '10%',
    width: '40%',
    justifyContent: 'space-around',
  },
  selected: {
    backgroundColor: '#e8e8e8',
    padding: 5,
    borderRadius: 5,
    textAlign: 'center',
    borderWidth: .5,
  },
  unselected: {
    backgroundColor: '#b5b5b5',
    padding: 5,
    borderRadius: 5,
    textAlign: 'center',
    borderWidth: .5,
  },
  cdPlayer: {
    backgroundColor: 'white',
    height: '35%',
    width: '75%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trackView: {
    height: '95%',
    width: '100%',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  currentTrack: {
    height: '70%',
    width: '65%',
    backgroundColor: '#E0EBE7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
    borderWidth: .2,
  },
  trackContainers: {
    height: '70%',
    width: '17%',
    backgroundColor: 'white',
    alignItems: 'center',
  },
  prevNextTrack: {
    height: '25%',
    width: '80%',
    backgroundColor: '#E0EBE7',
    borderRadius: 25,
    borderWidth: .5,
    justifyContent: 'center',
  }
});
